using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TacticalMaddiAdminTool.ViewModels;

namespace TacticalMaddiAdminTool.Services
{
    public class ItemsProvider
    {
        public ItemViewModel[] LoadItems()
        {
            var itemViewModels = new[]
            {
                new ItemViewModel{ Title = "LdnClose", ItemType = "Sets"},
                new ItemViewModel{ Title = "NykCLose", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Test", ItemType = "Sets"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection1", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection2", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection3", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Collections/Collection4", ItemType = "Collections"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment1", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment2", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment3", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment4", ItemType = "Fragments"},
                new ItemViewModel{ Title = "Bank/Default/Fragments/Fragment5", ItemType = "Fragments"},
            };

            return itemViewModels;
        }

    }
}
